### ISSUE TITLE
Long coding language name out of range

### ISSUE THREAD

**Issue by lin-tianyu** [omsimos/github-stats#10]
![image](https://github.com/user-attachments/assets/12e9fc95-2725-4de2-a851-4f162f7a098b)

Hi author, love your work. But when I use it, there will be an out-of-range problem if the coding language is too long. (Ex: the Jyputer Notebook 2.0 shown above)

It would be nice if the stats could auto-adjust!

**Comment by joshxfi** [comment]
hello @lin-tianyu, thank you for your feedback and for bringing this issue to our attention. seems like we needed to put an option for `card_width`, we'll take note of this.

in the meantime, you can manually add `&card_width={number}` to your URL.

**sample url:**
`https://github-readme-stats.vercel.app/api/top-langs/?username=lin-tianyu&theme=default&show_icons=true&hide_border=true&layout=compact&card_width=350`

**preview:**
![GitHub Stats](https://github-readme-stats.vercel.app/api/top-langs/?username=lin-tianyu&theme=default&show_icons=true&hide_border=true&layout=compact&card_width=350)

**Comment by lin-tianyu** [comment]
Thanks for your response!
