### ISSUE TITLE
NO STATS

### ISSUE THREAD

**Issue by hassony105** [omsimos/github-stats#11]
Hello,

My friend (@lightbringer95) when using this feature do not have stats event the streak and most language usage also works.
Note: if you visit the profile you with see there are many stats!

![GitHub Stats](https://github-readme-stats.vercel.app/api?username=lightbringer95&theme=dark&show_icons=true&hide_border=true&count_private=true)
![GitHub Stats](https://github-readme-stats.vercel.app/api/top-langs/?username=lightbringer95&theme=dark&show_icons=true&hide_border=true&layout=compact)
![GitHub Stats](https://github-readme-streak-stats.herokuapp.com/?user=lightbringer95&theme=dark&hide_border=true)
![Screenshot 2024-09-07 160556](https://github.com/user-attachments/assets/fbb0b09c-c562-43cc-a880-4276fbd8c1d8)

**Comment by joshxfi** [comment]
hello there! @hassony105 

there are instances where the server (from the API we use) gets too many requests and needs time to recover. It may still show to some because of caching. there may also be cases where the username is incorrect.

we will soon be self-hosting the APIs we use to handle the traffic load. let me know if this answers your issue!

**Comment by hassony105** [comment]
I have tried many different times, but still the same. also I do not think its caching problem because we have the it along time ago.
We checked the profile, especially:
## Contributions & activity

- [ ] Make profile private and hide activity
<sub>Enabling this will hide your contributions and activity from your GitHub profile and from social features like followers, stars, feeds, leaderboards and releases.</sub>

- [x] Include private contributions on my profile

<sub>Your contribution graph, achievements, and activity overview will show your private contributions without revealing any repository or organization information. [Read more](https://docs.github.com/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/viewing-contributions-on-your-profile).</sub>

---
We thank you for this repo and information, we will waiting to:

> self-hosting API

**Comment by joshxfi** [comment]
you're welcome! we'll be self-hosting the APIs used on the next update 🙌
